apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mesh-manager.nadundesilva.github.io/v1alpha1",
          "kind": "Microservice",
          "metadata": {
            "name": "microservice",
            "namespace": "microservice-sample"
          },
          "spec": {
            "dependencies": [
              {
                "name": "microservice-dependency",
                "namespace": "microservice-sample"
              }
            ],
            "podSpec": {
              "containers": [
                {
                  "image": "nginx:1.14.2",
                  "name": "nginx",
                  "ports": [
                    {
                      "containerPort": 80
                    }
                  ]
                }
              ]
            },
            "replicas": 1
          }
        },
        {
          "apiVersion": "mesh-manager.nadundesilva.github.io/v1alpha1",
          "kind": "Microservice",
          "metadata": {
            "name": "microservice-dependency",
            "namespace": "microservice-sample"
          },
          "spec": {
            "podSpec": {
              "containers": [
                {
                  "image": "nginx:1.14.2",
                  "name": "nginx",
                  "ports": [
                    {
                      "containerPort": 80
                    }
                  ]
                }
              ]
            },
            "replicas": 1
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.24.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: mesh-manager.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Microservice is the Schema for the microservices API
      displayName: Microservice
      kind: Microservice
      name: microservices.mesh-manager.nadundesilva.github.io
      version: v1alpha1
  description: Operator for microservices deployment
  displayName: Mesh Manager
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mesh-manager.nadundesilva.github.io
          resources:
          - microservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mesh-manager.nadundesilva.github.io
          resources:
          - microservices/finalizers
          verbs:
          - update
        - apiGroups:
          - mesh-manager.nadundesilva.github.io
          resources:
          - microservices/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: mesh-manager-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: mesh-manager-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: nadunrds/mesh-manager:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mesh-manager-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: mesh-manager-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - microservices
  - deployment
  links:
  - name: Mesh Manager
    url: https://nadundesilva.github.io/projects/personal
  maintainers:
  - email: nadunrds@gmail.com
    name: nadundesilva
  maturity: alpha
  provider:
    name: Nadun De Silva
    url: https://nadundesilva.github.io
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    conversionCRDs:
    - microservices.mesh-manager.nadundesilva.github.io
    deploymentName: mesh-manager-controller-manager
    generateName: cmicroservices.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: mesh-manager-controller-manager
    failurePolicy: Fail
    generateName: mmicroservice.kb.io
    rules:
    - apiGroups:
      - mesh-manager.nadundesilva.github.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - microservices
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-mesh-manager-nadundesilva-github-io-v1alpha1-microservice
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: mesh-manager-controller-manager
    failurePolicy: Fail
    generateName: vmicroservice.kb.io
    rules:
    - apiGroups:
      - mesh-manager.nadundesilva.github.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - microservices
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-mesh-manager-nadundesilva-github-io-v1alpha1-microservice
