# permissions for end users to edit dependantslice.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dependantslice-editor-role
rules:
- apiGroups:
  - mesh-manager.nadundesilva.github.io
  resources:
  - dependantslice
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh-manager.nadundesilva.github.io
  resources:
  - dependantslice/status
  verbs:
  - get
