# permissions for end users to edit microservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservice-editor-role
rules:
- apiGroups:
  - mesh-manager.nadundesilva.github.io
  resources:
  - microservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh-manager.nadundesilva.github.io
  resources:
  - microservices/status
  verbs:
  - get
