## Append samples you want in your CSV to this file as resources ##
resources:
- mesh-manager_v1alpha1_application.yaml
- mesh-manager_v1alpha1_dependantslice.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
