apiVersion: mesh-manager.nadundesilva.github.io/v1alpha1
kind: Application
metadata:
  name: application-sample-dependency
spec:
  podSpec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
---
apiVersion: mesh-manager.nadundesilva.github.io/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  podSpec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
  dependencies:
  - name: application-sample-dependency
