apiVersion: mesh-manager.nadundesilva.github.io/v1alpha1
kind: Microservice
metadata:
  name: microservice-dependency
spec:
  podSpec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
---
apiVersion: mesh-manager.nadundesilva.github.io/v1alpha1
kind: Microservice
metadata:
  name: microservice
spec:
  podSpec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
  dependencies:
  - name: microservice-dependency
