
name: Build

on:
    workflow_call:
        inputs:
            publish-snapshots:
                description: Whether the snapshots should be published (true/false)
                required: true
                type: string
        secrets:
            docker_hub_token:
                description: Docker Hub token
                required: true

jobs:
    run-super-linter:
        name: Run GitHub Super Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_ALL_CODEBASE: "true"
                  VALIDATE_GO: "false"
                  VALIDATE_KUBERNETES_KUBEVAL: "false"
                  KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas

    run-codeql-analysis:
        name: Run CodeQL Analysis
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: go
            - name: Autobuild
              uses: github/codeql-action/autobuild@v2
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2

    build:
        name: Build
        runs-on: ubuntu-latest
        needs:
            - run-super-linter
            - run-codeql-analysis
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v3
              with:
                  go-version: "^1.18"
            - name: Building Controller
              run: make docker-build
              env:
                  IMG: "nadunrds/mesh-manager:${{ github.sha }}"
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/mesh-manager:${{ github.sha }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
            # - name: Pushing Controller
            #   run: make docker-push
            #   env:
            #       IMG: "nadunrds/mesh-manager:${{ github.sha }}"
