
name: Build

on:
    workflow_call:
        inputs:
            publish-snapshots:
                description: Whether the snapshots should be published (true/false)
                required: true
                type: string
        secrets:
            docker_hub_token:
                description: Docker Hub token
                required: true

jobs:
    check-code-gen:
        name: Check Code Generation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v3
              with:
                  go-version: "^1.18"
            - name: Generate code
              run: make generate manifests
            - name: Check for changes
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "There are new changes after the code generation. Please run 'make gen' and commit the changes"
                    exit 1
                  fi

    check-code:
        name: Check Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Vet Code
              run: make vet
            - name: Check Code Format
              run: |
                  make fmt
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "There are new changes after the code format. Please run 'make fmt' and commit the changes"
                    exit 1
                  fi

    run-super-linter:
        name: Run GitHub Super Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_ALL_CODEBASE: "true"
                  VALIDATE_GO: "false"
                  VALIDATE_KUBERNETES_KUBEVAL: "false"
                  KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas

    run-codeql-analysis:
        name: Run CodeQL Analysis
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: go
            - name: Autobuild
              uses: github/codeql-action/autobuild@v2
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2

    build-operator:
        name: Build Operator
        runs-on: ubuntu-latest
        needs:
            - check-code-gen
            - check-code
            - run-super-linter
            - run-codeql-analysis
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v3
              with:
                  go-version: "^1.18"
            - name: Login to the Container registry
              if: ${{ inputs.publish-snapshots != '' }}
              uses: docker/login-action@v2
              with:
                  username: nadunrds
                  password: ${{ secrets.docker_hub_token }}
            - name: Building Controller
              run: make docker-build
              env:
                  IMG: "nadunrds/mesh-manager-operator:${{ github.ref_name }}"
            - name: Run Trivy vulnerability scanner on Controller
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/mesh-manager-operator:${{ github.ref_name }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
            - name: Pushing Controller
              run: make docker-push
              env:
                  IMG: "nadunrds/mesh-manager-operator:${{ github.ref_name }}"
            - name: Building Controller Bundle
              run: make docker-build
              env:
                  IMG: "nadunrds/mesh-manager-operator-bundle:${{ github.ref_name }}"
            - name: Run Trivy vulnerability scanner on Controller Bundle
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/mesh-manager-operator-bundle:${{ github.ref_name }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
            - name: Pushing Controller Bundle
              run: make docker-push
              env:
                  IMG: "nadunrds/mesh-manager-operator-bundle:${{ github.ref_name }}"
