name: Build

on:
  workflow_call:
    inputs:
      version:
        description: The version of the artifacts to be built
        required: true
        type: string
      publish-artifacts:
        description: Whether the artifacts should be published (true/false)
        type: boolean
        default: false
      update-latest-tag:
        description: Whether the latest tag should be updated to the current build (true/false)
        type: boolean
        default: false
    secrets:
      docker-hub-token:
        required: false
        description: Docker Hub token

permissions:
  contents: read
  packages: read

env:
  IMAGE_TAG_BASE: nadunrds/mesh-manager

jobs:
  check-code-gen:
    name: Check Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup GoLang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: "1.25.1"
      - name: Generate code
        run: make bundle
        env:
          ARTIFACTS_VERSION: ${{ inputs.version }}
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are new changes after the code generation. Please run 'make bundle' and commit the changes"
            git diff -p
            exit 1
          fi

  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup GoLang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: "1.25.1"
      - name: Vet Code
        run: make vet
      - name: Lint Code
        run: make lint
      - name: Check Code Format
        run: |
          make fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are new changes after the code format. Please run 'make fmt' and commit the changes"
            exit 1
          fi

  run-super-linter:
    name: Run GitHub Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build Kustomize manifests
        run: make manifests
        env:
          IMG: ${{ env.IMAGE_TAG_BASE }}:${{ github.sha }}
      - name: Lint Code Base
        uses: super-linter/super-linter@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: "true"
          VALIDATE_CHECKOV: "false"
          VALIDATE_GO: "false"
          VALIDATE_GO_MODULES: "false"
          VALIDATE_YAML_PRETTIER: "false"
          VALIDATE_KUBERNETES_KUBEVAL: "false"
          VALIDATE_KUBERNETES_KUBECONFORM: "false"
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas

  run-vulnerability-analysis:
    name: Run Vulnerability Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: fs
          vuln-type: library
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

  validate-bundle:
    name: Run Operator Bundle Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Validate Bundle
        run: |
          make bundle

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup GoLang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: "1.25.1"
      - name: Run Unit Tests
        run: make test.unit

  build-operator:
    name: Build Operator
    runs-on: ubuntu-latest
    needs:
      - check-code-gen
      - check-code
      - validate-bundle
      - run-super-linter
      - run-vulnerability-analysis
      - run-unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup GoLang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: "1.25.1"
      - id: generate-bundle-version
        name: Generate Bundle Version
        env:
          ARTIFACTS_VERSION: ${{ inputs.version }}
        run: |
          echo "bundle-version=${ARTIFACTS_VERSION/\//-}" >> "${GITHUB_OUTPUT}"
      - name: Generate code
        run: make generate manifests bundle
        env:
          VERSION: "${{ steps.generate-bundle-version.outputs.bundle-version }}"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Setup Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Print Available Buildx Platforms
        run: echo "${SUPPORTED_PLATFORMS}"
        env:
          SUPPORTED_PLATFORMS: ${{ steps.setup-buildx.outputs.platforms }}
      - name: Build Controller
        run: make docker-build
        env:
          VERSION: "${{ steps.generate-bundle-version.outputs.bundle-version }}"
      - name: Run Trivy vulnerability scanner on Controller
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: ${{ env.IMAGE_TAG_BASE }}:${{ steps.generate-bundle-version.outputs.bundle-version }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          trivyignores: .trivyignore.controller

      - name: Building Controller Bundle
        run: make bundle-build
        env:
          VERSION: "${{ steps.generate-bundle-version.outputs.bundle-version }}"
      - name: Run Trivy vulnerability scanner on Controller Bundle
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: ${{ env.IMAGE_TAG_BASE }}-bundle:${{ steps.generate-bundle-version.outputs.bundle-version }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          trivyignores: .trivyignore.bundle

      - name: Login to the Container registry
        if: ${{ inputs.publish-artifacts == true }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: nadunrds
          password: ${{ secrets.docker-hub-token }}
      - name: Pushing Controller
        if: ${{ inputs.publish-artifacts == true }}
        run: make docker-buildx
        env:
          VERSION: "${{ steps.generate-bundle-version.outputs.bundle-version }}"
      - name: Pushing Controller Bundle
        if: ${{ inputs.publish-artifacts == true }}
        run: make bundle-push
        env:
          VERSION: "${{ steps.generate-bundle-version.outputs.bundle-version }}"

      - name: Pushing Controller with latest Tag
        if: ${{ inputs.publish-artifacts == true && inputs.update-latest-tag == true }}
        run: make docker-buildx
        env:
          VERSION: "latest"
      - name: Pushing Controller Bundle with latest Tag
        if: ${{ inputs.publish-artifacts == true && inputs.update-latest-tag == true }}
        run: make bundle-push
        env:
          VERSION: "latest"

    outputs:
      bundle-version: ${{ steps.generate-bundle-version.outputs.bundle-version }}

  validate-multi-architecture-bundle:
    name: Validate Bundle Multi Architecture Support
    runs-on: ubuntu-latest
    if: ${{ inputs.publish-artifacts == true }}
    needs:
      - build-operator
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Validate Bundle
        run: |
          make operator-sdk
          ./bin/operator-sdk bundle validate "${IMAGE_TAG_BASE}-bundle:${VERSION}" \
            --select-optional name=multiarch
        env:
          VERSION: "${{ needs.build-operator.outputs.bundle-version }}"
