name: Vulnerabilities Scan

on:
    workflow_run:
        workflows:
            - Release
        types:
            - completed
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
        inputs:
            image-tag:
                description: Docker Image tag
                required: true
                default: latest
                type: string

jobs:
    operator-run-trivy-scan:
        name: Run Trivy Scan
        runs-on: ubuntu-latest
        steps:
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/mesh-manager-operator:${{ github.event.inputs.image-tag || 'main' }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true

    operator-bundle-run-trivy-scan:
        name: Run Trivy Scan
        runs-on: ubuntu-latest
        steps:
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/mesh-manager-operator-bundle:${{ github.event.inputs.image-tag || 'main' }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
